### ISSUE TITLE
still alive?

### ISSUE THREAD

**Issue by kduvekot-wehkamp-nl** [elsevierlabs-os/spark-xml-utils#2]
I might have a use case for XML parsing, transformation etc .. but than using spark 3 ... 
Is there still someone actively using this?

**Comment by dmcbeath** [comment]
Yes, we actively use it and are using it with no problems on Spark 3.  Do you have any specific questions or are you running into any specific issues?

**Comment by kduvekot-wehkamp-nl** [comment]
no .. but when I see a potentially useful tool .. with no issues logged .. and last update a long time ago .. I am a bit "hesitant" to start using it .. 
So now that I know it also works under spark 3 .. I will start to play around with it ... 

thanks for the quick response :+1:
