### ISSUE TITLE
update dependencies to "current" versions

### ISSUE THREAD

**Issue by kduvekot-wehkamp-nl** [elsevierlabs-os/spark-xml-utils#3]
Would it be possible to update this tool dependencies to current versions?

dependency | used version | current version
------------ | ------------- | ------------- 
Saxon-HE | 9.8.0-6 | 10.5
commons-io  |  2.4 | 2.8
commons-logging | 1.2 | 1.2 
commons-lang3 | 3.4 | 3.12.0

**Comment by dmcbeath** [comment]
I'll take a look later this week.

**Comment by dmcbeath** [comment]
The dependencies have been updated.  I will get the new jar to maven later today.  Let me know if you have any other questions or experience any problems.

**Comment by kduvekot-wehkamp-nl** [comment]
I will do the testing with the examples tomorrow  ... thanks :+1:

**Comment by dmcbeath** [comment]
One thing I've noticed is the new artifact release (1.9.0) is not being picked up by the central mvn repository.  I saw this post earlier https://spark.apache.org/news/new-repository-service.html (which was posted April 28) and I'm wondering if something needs to change for the central mvn repository to pick up the new packages.  I've sent them a note asking this question this morning.

**Comment by kduvekot-wehkamp-nl** [comment]
okee ... when you know more .. just add it here ...

**Comment by dmcbeath** [comment]
I received a reply from the group (I believe Databricks) responsible for spark-packages.  They confirmed that the new repository they migrated to in early May (referenced in the above comment) is currently not being indexed by the central Maven repository.  I'm not sure what their current plans are, but I provided them my feedback and the need to get their new repository indexed by the central Maven repository.  I will let you know as soon as I learn more.  For now, the best solution would be to clone spark-xml-utils locally and install into your own local maven repository until this gets sorted.  Apologies for the inconvenience.

**Comment by dmcbeath** [comment]
So, here is the official recommendation from spark-packages.org.  I don't see them taking steps to get spark-packages indexed by Maven central (they said I should submit a jira ticket to Maven central to get that done).  With that said, below is their recommendation.

spark-packages.org should be the source of truth for artifacts registered at spark-packages.org (not Maven central).  This makes sense.

If you are using maven and a pom.xml to build an application that includes an artifact from spark-packages.org (such as spark-xml-utils) then you would want to specify the repository (repos.spark-packages.org) for spark-packages.org. Details for how to specify repositories in the pom.xml can be found at [https://maven.apache.org/guides/mini/guide-multiple-repositories.html](https://maven.apache.org/guides/mini/guide-multiple-repositories.html).  Similar adjustments would be made for sbt.

If you are using --packages to specify artifacts on spark-packages, with spark-submit, spark-shell, etc., you need to set the environment variable DEFAULT_ARTIFACT_REPOSITORY to https://repos.spark-packages.org/, before Spark 2.4.8, 3.0.3 and 3.1.2 are released.

**Comment by kduvekot-wehkamp-nl** [comment]
great ... I am using spark on databricks .. and the spark-packages is already included in their default maven search option:
![image](https://user-images.githubusercontent.com/13831273/117840566-92972580-b27c-11eb-8dbb-4ce95fd3ffc0.png)
and I can select 1.9.0 .. so I am going to test with that one.

Thanks for helping out .. and thanks for the update.
